resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 100m
ingress:
  class: ""
  host: ~
  path: /eam-web(/|$)(.*)
  rewriteTarget: eam-web/$2
image:
  repository: ghcr.io/mbit9i/eam_app
  tag: latest
  pullPolicy: Always
  pullSecret: github-reader
service:
  replicas: 1
  internalPort: 80 
  externalPort: 80