apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    {{ if .Values.ingress.rewriteTarget }}
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.rewriteTarget }}
    {{- end }}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/client-body-buffer-size: 100M
    nginx.ingress.kubernetes.io/proxy-body-size: 100M
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  {{- if .Values.ingress.class }}
  ingressClassName: {{ .Values.ingress.class }}
  {{- end }}
  rules:
  {{ if .Values.ingress.host }}
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /
        backend:
          service:
            name: {{ .Release.Name }}-service
            port: 
              number: {{ .Values.service.externalPort }}
  {{- else }}
  - http:
      paths:
      - pathType: ImplementationSpecific
        path: /eam-web-new(/|$)(.*)
        backend:
          service:
            name: {{ .Release.Name }}-application
            port:
              number: {{ .Values.service.externalPort }}
  {{- end }}
  