apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-application
  labels:
    apps: {{ .Release.Name }}-application
    release: {{ .Release.Name }}-application
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    name: http
  selector:
    app: {{ .Release.Name }}-application