name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build and Push the Docker image
      run: |
        docker login --username MbIT9I --password ${{ secrets.GHCR_TOKEN }} ghcr.io 
        docker build . --file Dockerfile --tag ghcr.io/mbit9i/eam_app:latest
        docker push ghcr.io/mbit9i/eam_app:latest

  deploy:

    runs-on: self-hosted
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      uses: WyriHaximus/github-action-helm3@v3
      with:
        exec: helm upgrade APP_NAME ./.helm/app/ --install --wait --atomic --namespace=APP_NAMESPACE --values=./.helm/app/values.yaml
        kubeconfig: '${{ secrets.KUBE_CONFIG_DATA }}'
        overrule_existing_kubeconfig: "true"