name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # prepere:

  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: update minor appversion value with buildId in Chart.yaml
  #     run: |
  #       sed -i "" "s/\(appVersion: \)[0-9.]*/\11.0.${{ github.run_id }}/g" ./chart/Chart.yaml 
  #       cat ./chart/Chart.yaml
  #   - name: write ./chart/Chart.yaml file to artifact
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: Chart.yaml
  #       path: ./chart/Chart.yaml


  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and Push the Docker image
      run: |
        docker login --username MbIT9I --password ${{ secrets.GHCR_TOKEN }} ghcr.io 
        docker build . --file Dockerfile --tag ghcr.io/mbit9i/eam_app:1.0.${{ github.run_id }}
        docker push ghcr.io/mbit9i/eam_app:1.0.${{ github.run_id }}

  deploy:

    runs-on: self-hosted
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - name: update minor appversion value with buildId in Chart.yaml
      run: |
        (Get-Content -Path ./chart/Chart.yaml) | ForEach-Object { $_ -replace '^(appVersion:\s*)[0-9.]*', "`$1'1.0.${env:GITHUB_RUN_ID}'" } | Set-Content -Path ./chart/Chart.yaml
        Get-Content -Path ./chart/Chart.yaml
    
    - name: deploy via powershell
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        HELM_EXPERIMENTAL_OCI: 1
      run: |
        $env:KUBE_CONFIG_DATA | Out-File -FilePath .kubeconfig -Encoding utf8
        helm upgrade eam-web-new ./chart --install -f ./chart/values.yaml -n default --atomic --wait --set image.tag=1.0.${{ github.run_id }} --debug --kubeconfig .kubeconfig